language: java

jdk: 
    - oraclejdk8
    - openjdk8

matrix:
    include:
        - os: linux
          jdk:
            - oraclejdk8
            - openjdk8
        - os: osx
          jdk: oraclejdk8

script: ./run-all.sh

