jdk:
    - oraclejdk8

jobs:
  include:
    - stage: slllist
      script: ./.run_test.sh sllist
    - stage: refSLL 
      script: ./.run_test.sh RefSLL
    - stage: refDLL
      script: ./.run_test.sh RefDLL
    - stage: refBTDLL
      script: ./.run_test.sh RefBTDLL
    - stage: refBT
      script: ./.run_test.sh RefBT
    - stage: bimap 
      script: ./.run_test.sh bimap
    - stage: avltree 
      script: ./.run_test.sh avltree 
