jdk:
    - oraclejdk8

jobs:
  include:
    - stage: list
      script: ./.run_test.sh sllist
    - stage: refBT
      script: ./.run_test.sh RefBT
    - stage: refSLL 
      script: ./.run_test.sh RefSLL
      #    - stage: refDLL
      #script: ./.run_test.sh RefDLL
    - stage: refBTDLL
      script: ./.run_test.sh RefBTDLL
    - stage: avltree 
      script: ./.run_test.sh avltree 
