language: java
jdk: oraclejdk8

jobs:
  include:
    - stage: Singly-Linked-List-Manual
      script: ./.run_test.sh sllist
    - stage: Singly-Linked-List
      script: ./.run_test.sh RefSLL
    - stage: Doubly-Linked-List
      script: ./.run_test.sh RefDLL
    - stage: Binary-Tree
      script: ./.run_test.sh RefBT
    - stage: Bidirectional-Map
      script: ./.run_test.sh bimap
    - stage: AVL-Tree
      script: ./.run_test.sh avltree 
